version: '3.1'

services:
  deno:
    build: .
    ports:
      - "8000:${PORT}"
    volumes:
      - .:/usr/src/app
    depends_on: 
      - db
    
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password --init-file /data/application/init.sql
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB}
    ports:
      - 3306:3306
    restart: always
    volumes:
      - ./sql/init.sql:/data/application/init.sql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  swagger_ui:
    container_name: swagger_ui_service
    image: swaggerapi/swagger-ui
    ports:
      - "8105:8080"
    volumes:
      - ./openapi.yml:/openapi.yml
    environment:
      SWAGGER_JSON: /openapi.yml