version: '3.1'

services:
  restapi:
    build: .
    command: npm start
    ports:
      - "8000:${PORT}"
    volumes:
      - .:/usr/src/app
    depends_on: 
      - db
    
  db:
    image: postgres:latest
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    restart: always
    ports:
      - 5432:5432
    volumes: 
      - db:/var/lib/postgresql/data
      
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  swagger_ui:
    container_name: swagger_ui_service
    image: swaggerapi/swagger-ui
    ports:
      - "8105:8080"
    volumes:
      - ./openapi.yml:/openapi.yml
    environment:
      SWAGGER_JSON: /openapi.yml

volumes:
  db:
  local_pgdata:
  pgadmin-data: